apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: frontend-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: bjoernkjaer/frontend-service:0.1
        ports:
        - containerPort: 8000
        env:
        - name: MESSAGE
          value: Hello from the first deployment!
