apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: app.simplebar.dk
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend-service
          servicePort: 80
